spring:
  data:
    cassandra:
      username: cassandra
      password: cassandra
      keyspace: urlkeyspace 
      port: 9042
      contact-points: localhost,127.0.0.1
      schema-action: CREATE_IF_NOT_EXISTS
      
      
server:
  port: 5555
