version: '3.7'
services:
  urlshortener-redis:
    container_name: urlshortener-redis
    image: redis:alpine
    expose:
    - 6370
    ports:
    - 6370:6370
    
  cassandra:
    container_name: urlshortener-cassandra
    image: cassandra:3
    ports:
      - '7000:7000'
      - '9042:9042'
    
volumes:
  cassandra_data:
    driver: local